openapi: 3.0.0

info:
  description: |
    ## Q서비스 Webview에 제공하는 Android Native 함수 목록
    ***
    ## 참고
    - Swagger 문법에 맞추기 위해 모든 API가 POST로 되어 있음
    - 일반적으로 제공되는 함수의 Parameter는 String(json)
    - Request Body 부분이 해당 함수의 Parameter는 String(json)이다.
  version: "1.0.0"
  title: QService Android Webview Bridge
tags:
  - name: 촬영
  - name: 녹취
  - name: 입력
  - name: 전자문서
  - name: 임시저장
  - name: 업무(기타)

paths:
  /logout:
    post:
      tags:
        - 업무(기타)
      summary: 로그아웃
      operationId: logout
      description: |
        로그아웃 호출
      parameters:
      responses:

  /getUserInfo:
    post:
      tags:
        - 업무(기타)
      summary: 유저 정보 호출
      operationId: getUserInfo
      description: |
        유저 정보 호출
      responses:
        '200':
          description: 작성완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetUserInfo'

  /getNewToken:
    post:
      tags:
        - 업무(기타)
      summary: 새로운 토큰 호출
      operationId: getNewToken
      description: |
        새로운 토큰 호출
      parameters:
        - in: query
          name: json
          description: Json String, Request Body를 참고
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetNewToken'
      responses:


  /docCamera:
    post:
      tags:
        - 촬영
      summary: 문서촬영 카메라 호출
      operationId: docCamera
      description: |
        문서촬영 카메라 호출
      parameters:
        - in: query
          name: json
          description: Json String, Request Body를 참고
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestDocCamera'
      responses:
        '200':
          description:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDocCamera'

  /authCamera:
    post:
      tags:
        - 촬영
      summary: 신분증 인식 카메라 호출
      operationId: authCamera
      description: |
        신분증 인식 카메라 호출
      parameters:
        - in: query
          name: json
          description: Json String, Request Body를 참고
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestAuthCamera'
            examples:
              주민등록증/운전면허증 [카메라 촬영]:
                $ref: '#/components/examples/RequestAuthCamera1'
              주민등록증/운전면허증 [직접 입력]:
                $ref: '#/components/examples/RequestAuthCamera2'
              재외국민용 주민등록증 [카메라 촬영]:
                $ref: '#/components/examples/RequestAuthCamera3'
              재외국민용 주민등록증 [직접 입력]:
                $ref: '#/components/examples/RequestAuthCamera4'
              외국인등록증 [카메라 촬영]:
                $ref: '#/components/examples/RequestAuthCamera5'
              국내거소신고증 [카메라 촬영]:
                $ref: '#/components/examples/RequestAuthCamera6'
              여권 [카메라 촬영]:
                $ref: '#/components/examples/RequestAuthCamera7'


      responses:
        '200':
          description:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseAuthCamera'










  /clearBusiness:
    post:
      tags:
        - 업무(기타)
      summary: 현재 진행중인 상품을 캐시에서 삭제 요청
      operationId: clearBusiness
      description: |
        현재 진행중인 상품을 캐시에서 삭제 요청
      parameters:
      responses:

  /previewDoc:
    post:
      tags:
        - 촬영
      summary: 첨부 문서 미리보기
      operationId: previewDoc
      description: |
        첨부 문서 미리보기
      parameters:
        - in: query
          name: json
          description: Json String, Request Body를 참고
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestPreviewDoc'
      responses:

  /genEntryId:
    post:
      tags:
        - 업무(기타)
      summary: 전자문서 키 생성
      operationId: genEntryId
      description: |
        전자문서 키 생성
      parameters:
        - in: query
          name: json
          description: Json String, Request Body를 참고
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetEntryId'
      responses:
        '200':
          description: example을 참고
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetEntryId'
              examples:
                entryId 발급 성공 시:
                  $ref: '#/components/examples/ResponseGetEntryIdSuccess'
                entryId 발급 실패 시:
                  $ref: '#/components/examples/ResponseGetEntryIdFail'

  /secureKeyPad:
    post:
      tags:
        - 입력
      summary: 보안키패드 입력
      operationId: secureKeyPad
      description: |
        보안키패드 입력
      parameters:
        - in: query
          name: json
          description: Json String, Request Body를 참고
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestSecureKeyPad'
      responses:
        '200':
          description: example을 참고
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSecureKeyPad'

  /openSetting:
    post:
      tags:
        - 업무(기타)
      summary: Setting 화면 호출
      operationId: openSetting
      description: |
        Setting 화면 호출
      responses:

  /writePen:
    post:
      tags:
        - 입력
      summary: 펜입력
      operationId: writePen
      description: |
        펜입력
      parameters:
        - in: query
          name: json
          description: Json String, Request Body를 참고
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestWritePen'
            examples:
              pen:
                $ref: '#/components/examples/RequestWritePen_pen'

      responses:
        '200':
          description: example을 참고
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWritePen'

  /recordStart:
    post:
      tags:
        - 녹취
      summary: 녹음코드 전송
      operationId: recordStart
      description: |
        녹음코드 전송
      parameters:
        - in: query
          name: json
          description: Json String, Request Body를 참고
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestRecordStart'
      responses:
        '200':
          description: example을 참고
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseRecordStart'

  /recordEnd:
    post:
      tags:
        - 녹취
      summary: 녹음 종료 호출
      operationId: recordEnd
      description: |
        녹음 종료 호출
      responses:

  /openElectronicDocument:
    post:
      tags:
        - 전자문서
      summary: 전자문서 작성
      operationId: openElectronicDocument
      requestBody:
        required: true
        description: example
        content:
          application/json:
            example:
              step: 1.0
              title: "신청서작성"
              tabs:
                - businessLogic: "IZ000001"
                  title: "탭1"
                  appendForms:
                    - "10107100"
                    - "Z0000001"
                  images:
                    - "sign"
                  set:
                    name: "홍길동"
                    birth: "19880120"
                    sign: "wegagf"
                  get:
                    - "name"
                    - "birth"
              shouldTransaction: true
            schema:
              $ref: '#/components/schemas/WebElectronicDocumentData'
      responses:
        '200':
          description: example을 참고
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElectronicDocumentResult'


  /previewElectronicDocument:
    post:
      tags:
        - 전자문서
      summary: 전자문서를 미리보기로 전환
      operationId: previewElectronicDocument
      requestBody:
        required: true
        content:
          application/json:
            example:
              ecc:
                IZ0001:
                  "PRINT1": "이름 : 홍길동"
                IZ0002:
                  "PRINT2": "생년월일 : 19880120"

            schema:
              $ref: '#/components/schemas/WebPreviewElectronicDocument'
      responses:
        '200':
          description: example을 참고
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElectronicDocumentResult'

  /openElectronicDocumentPreview:
    post:
      tags:
        - 전자문서
      summary: 전자문서 미리보기
      operationId: openElectronicDocumentPreview
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: "미리보기"
              editable: true
            schema:
              $ref: '#/components/schemas/WebElectronicPreview'
      responses:
        '200':
          description: example을 참고
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElectronicDocumentResult'

  /uploadResult:
    post:
      tags:
        - 업무(기타)
      summary: 결과 업로드
      operationId: uploadResult
      requestBody:
        required: true
        content:
          application/json:
            example:
              {
                "data": {
                  "id": 999914,
                  "name": "모집인",
                  "clientName": "홍길동",
                  "test": true,
                  "terminalInfo": {
                    "data1": "전자문서 데이터1",
                    "data2": "전자문서 데이터2",
                    "data3": "전자문서 데이터3"
                  }
                }
              }
            schema:
              $ref: '#/components/schemas/WebUploadData'
      responses:
        '200':
          description: example을 참고
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebUploadResult'


  /clearFormStep:
    post:
      tags:
        - 임시저장
      summary: 지정한 스텝 이후의 스탭을 삭제
      operationId: clearFormStep
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClearFormStepData'
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClearFormStepResult'
        '400':
          description: "BAD_REQUEST"

  /uploadTemp:
    post:
      tags:
        - 임시저장
      summary: 임시저장 데이터 업로드
      operationId: uploadTemp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadTempData'
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadTempResult'
        '400':
          description: "BAD_REQUEST"

























components:
  schemas:
    WebElectronicDocumentData:
      type: object
      required:
        - tabs
      properties:
        step:
          type: float
          description: 단계
          example: 1.0
        title:
          type: string
          description: 제목
          example: "신청서작성"
        tabs:
          type: array
          description: 탭 정보
          nullable: false
          items:
            $ref: '#/components/schemas/Tab'
        shouldTransaction:
          type: boolean
          description: |
            거래여부 
            
            작성완료 후 웹에서 처리로직이 필요할 경우 true

          default: false
          example: true
    Tab:
      type: object
      required:
        - businessLogic
      properties:
        businessLogic:
          type: string
          nullable: false
          description: 비즈로직
          example: "IZ000001"
        title:
          type: string
          description: 탭 제목
          example: "탭1"
        appendForms:
          type: array
          items:
            type: string
          example: [ "10107100", "Z0000001" ]
          description: |
            추가로 열 서식
            
            비즈로직 내 openForms 뒤에 추가로 붙는다.
        images:
          type: array
          items:
            type: string
          example: [ "sign" ]
          description: set 목록 중 이미지 key 리스트
        set:
          type: object
          additionalProperties:
            type: string
          example:
            name: "홍길동"
            birth: "19880120"
            sign: "wegagf"
          description: |
            비즈로직에 set할 맵 데이터
            
            - key : String
            
            - value : String
        get:
          type: array
          items:
            type: string
          example: [ "name", "birth" ]
          description: 비즈로직에서 get할 데이터

    ElectronicDocumentResult:
      type: object
      required:
        - isComplete
      properties:
        isComplete:
          type: boolean
          example: true
          description: 완료여부
        resultRequest:
          type: object
          additionalProperties:
            type: object
          example:
            IZ0001: { "name": "홍길동" }
            IZ0002: { "birth": "19880120" }
          description: |
            전자문서에 요청한 추출한 데이터 
            
            - key : String 비즈로직
            
            - value : Map, key : 요청 key, value: 추출데이터
        fullData:
          type: object
          additionalProperties:
            type: object
          example:
            IZ0001: { "name": "홍길동" }
            IZ0002: { "birth": "19880120" }
          description: |
            전자문서에서 추출한 모든 데이터 
            
            - key : String 비즈로직
            
            - value : Map, key : 요청 key, value: 추출데이터

    WebPreviewElectronicDocument:
      type: object
      properties:
        ecc:
          type: object
          example:
            ecc:
              IZ0001:
                "PRINT1": "이름 : 홍길동"
              IZ0002:
                "PRINT2": "생년월일 : 19880120"
          additionalProperties:
            type: object
          description: |
            전자문서를 미리보기로 전환한다. 
            
            - key : String 비즈로직
            
            - value : Map, key : 요청 key, value: 삽입 데이터

    WebElectronicPreview:
      type: object
      properties:
        title:
          type: string
          description: 제목
        editable:
          type: boolean
          description: 수정 가능 여부
          default: false

    WebUploadData:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            type: object
          example:
            id: 999914
            name: "모집인"
            clientName: "홍길동"
            test: true
            terminalInfo:
              data1: "전자문서 데이터1"
              data2: "전자문서 데이터2"
              data3: "전자문서 데이터3"
          description: |
            업로드 시 Meta.json 파일에 쓰여질 정보, json string

    WebUploadResult:
      type: object
      required:
        - isComplete
      properties:
        isComplete:
          type: boolean
          description: 업로드 완료 여부

    ResponseGetUserInfo:
      type: object
      properties:
        brnNm:
          type: string
          example: "강남역 금융센터"
          description: 지점명
        brnNo:
          type: string
          example: "046"
          description: 지점코드
        chiefYn:
          type: string
          example: "N"
          description: ??(센터장추측)
        handPhone:
          type: string
          example: "010-1234-5678"
          description: 핸드폰
        jikgubCd:
          type: string
          example: "25"
          description: 직급코드
        jikgubNm:
          type: string
          example: "대리"
          description: 직급
        mailId:
          type: string
          example: "lhb1234@ibks.com"
          description: 메일주소
        name:
          type: string
          example: "홍길동"
          description: 이름
        orgCd:
          type: string
          example: "AA000000"
          description: 지점코드
        orgNm:
          type: string
          example: "강남역 금융센터"
          description: 지점명
        sabun:
          type: string
          example: "123456"
          description: 사번
      required:
        - brnNm
        - brnNo
        - handPhone
        - jikgubCd
        - jikgubNm
        - mailId
        - name
        - orgCd
        - orgNm
        - sabun

    RequestGetNewToken:
      type: object
      properties:
        sabun:
          type: string
          example: "171066"
          description: 사번
        brnNm:
          type: string
          example: "역삼"
          description: 지점명
      required:
        - sabun
        - brnNm

    RequestDocCamera:
      type: object
      properties:
        docCode:
          type: string
          example: "123456"
          description: 문서 코드(문서이미지 파일명이 됨)
        docName:
          type: string
          example: "주민등록등본"
          description: 문서 이름
        takeCount:
          type: string
          example: "3"
          description: 촬영 Max 갯수
        maskingYn:
          type: string
          example: "Y"
          description: 마스킹 필요 여부(Y or N)
      required:
        - docCode
        - docName
        - takeCount
        - maskingYn

    ResponseDocCamera:
      type: object
      properties:
        isComplete:
          type: boolean
          example: true
          description: 첨부 완료 여부(true or false)
        takeCountNum:
          type: string
          example: "3"
          description: 첨부한 갯수(1)
      required:
        - isComplete
        - takeCountNum



    RequestAuthCamera:
      type: object
      properties:
        authCode:
          type: string
          description: |
            코드값 (기본 "IDV0000")

            다른 코드 값을 사용해야 할 경우 사용

            대리인 ("IDV0001")
        cameraType:
          type: string
          example: "idcard"
          description: |
            신분증촬영: idcard

            그외 기타신분증:etccard
        takeType:
          type: string
          example: "ocr"
          description: |
            인식필요: ocr

            일반촬영: normal

            직접입력: direct
        requireIssueDate:
          type: string
          example: "Y"
          description: takeType이 ocr/direct 일 때 필수
        requireIssueOffice:
          type: string
          example: "Y"
          description: takeType이 ocr/direct 일 때 필수
      required:
        - cameraType
        - takeType



    ResponseAuthCamera:
      type: object
      properties:
        isAuthComplete:
          type: boolean
          description: |
            인증완료함: true

            인증안함: false
        authType:
          type: string
          description: |
            주민등록증: idcard

            운전면허증: drive_license

            인감: seal

            외국인등록증: foreign

            여권: passport

            재외국인: oversea

            국내거소신고증: compatriot
        takeType:
          type: string
          description: |
            인식필요: ocr

            일반촬영: normal

            직접입력: direct
        rrn:
          type: string
          description: |
            주민번호 해쉬코드

            N(인증성공 및 takeType이 ocr, direct일 경우만)
        birth:
          type: string
          description: |
            생년월일(6자리)
            
            N(인증성공 및 takeType이 ocr, direct일 경우만)
        name:
          type: string
          description: |
            이름
            
            N(인증성공 및 takeType이 ocr, direct일 경우만) 
        edocKey:
          type: string
          description: 전자문서키 키
        phone:
          type: string
          description: 휴대폰번호
        issuedDate:
          type: string
          description: 발급날짜
        issuedOffice:
          type: string
          description: 발급기관
        driveLicenseNo:
          type: string
          description: 운전면허번호
      required:
        - isAuthComplete
        - authType
        - takeType

    RequestPreviewDoc:
      type: object
      properties:
        docCode:
          type: string
          example: "123456"
          description: 문서 코드(문서이미지 파일명이 됨)
        docName:
          type: string
          example: "주민등록등본"
          description: 문서 이름
      required:
        - docCode
        - docName

    RequestGetEntryId:
      type: object
      properties:
        code:
          type: string
          example: "PRD"
          description: 업무코드
        subCode:
          type: string
          example: "PR002"
          description: '서브업무구분코드 default: "00000"'
        custName:
          type: string
          example: "홍길동"
          description: 고객명
        subNo:
          type: string
          example: "19950421"
          description: 고객생년월일 or 고객사업자번호
        custMpno:
          type: string
          example: "010-1234-1234"
          description: 고객전화번호
        refNo:
          type: string
          example: "test@inzisoft.com"
          description: 고객이메일
        onesfAgntTp:
          type: string
          example: "0"
          description: "본인 : 0, 대리인 : 1"
      required:
        - code
        - custName
        - subNo
        - custMpno
        - onesfAgntTp

    ResponseGetEntryId:
      type: object
      properties:
        result:
          type: boolean
          example: true
          description: 전자문서 키 생성 성공 여부
        etryId:
          type: string
          example: "PRDPR0021234567812345620221121OD000001"
          description: 생성한 전자문서 키
        errorMessage:
          type: string
          example: "연락처 유효성 검사 실패"
          description: 에러메시지
      required:
        - result

    RequestSecureKeyPad:
      type: object
      properties:
        title:
          type: string
          example: "주민번호 뒷자리 7자리"
          description: 타이틀
        isNumber:
          type: boolean
          example: true
          description: 'Y: 숫자키패드, N : 일반키패드(default)'
        placeholder:
          type: string
          example: "주민번호 뒷자리를 입력해주세요."
          description: 설명 문구
        maxLength:
          type: integer
          example: 7
          description: 입력 가능 최대 길이

    ResponseSecureKeyPad:
      type: object
      properties:
        enc:
          type: string
          example: "aW56aXNjdjIMAAAABwAAAAIAIAAAAKCG1OLFDN5OGLoegqLYz+VOvR5rGrfP3nf++pO/0IjBAQAQAAAA7snW1imj623FmfqDi9UMxAMABAAAABkAAAAEAAQAAAB+AAAABQAEAAAAIAAAAAYABAAAAM+CnZoHAAQAAACfaQNQnsvHrKjmLHSgsDvP2u9KXfuDy1OZzwzVcpJOZ/f68ZU="
          description: 암호화 데이터
        plain:
          type: string
          example: "*******"
          description: 입력한 길이만큼 * (필드에 삽입할 용도)
        decPart:
          type: string
          example: "1"
          description: 주민 뒷자리의 첫 자리
      required:
        - enc
        - plain
        - decPart

    RequestWritePen:
      type: object
      properties:
        type:
          type: string
          example: ""
          description: |
            펜 다이얼로그 타입
            
            PenDialog = "pen"
            
            PenSealDialog = "penseal"
            
            SealDialog =  "seal"
        title:
          type: string
          example: "따라쓰기"
          description: 제목
        pen:
          type: object
          properties:
            id:
              type: string
              example: "DDARA"
              description: 매핑 아이디
            subtitle:
              type: string
              example: "따라쓰기를 해주세요."
              description: 부제목
            placeholder:
              type: string
              example: "따라쓰기 입니다."
              description: 음영문구
          required:
            - id
        signPen:
          type: object
          properties:
            id:
              type: string
              example: "DDARA"
              description: 매핑 아이디
            subtitle:
              type: string
              example: "따라쓰기를 해주세요."
              description: 부제목
            placeholder:
              type: string
              example: "따라쓰기 입니다."
              description: 음영문구
          required:
            - id
        seal:
          type: object
          properties:
            id:
              type: string
              example: "DDARA"
              description: 매핑 아이디
            subtitle:
              type: string
              example: "따라쓰기를 해주세요."
              description: 부제목
            placeholder:
              type: string
              example: "따라쓰기 입니다."
              description: 음영문구
          required:
            - id
      required:
        - title

    ResponseWritePen:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            example: "DDARA"
          result:
            type: boolean
            example: true
          value:
            type: string
            example: "/storage/emulated/0/Android/data/com.inzisoft.ibks.itest/cache/PRDPR0021234567812345620221121OD000001/pen/DDARA.png"
        required:
          - id
          - result
          - value
      description: 작성 결과

    RequestRecordStart:
      type: object
      properties:
        records:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                example: "ROV0000T"
                description: '1차 오픈 : "ROV0000T" 고정'
              name:
                type: string
                example: "녹취"
                description: '1차 오픈 : "녹취" 고정'
            required:
              - code
              - name
          description: 녹취 해야할 코드 목록(1차오픈 1개)
      required:
        - records

    ResponseRecordStart:
      type: boolean
      example: true

    UploadTempData:
      type: object
      properties:
        step:
          type: string
          example: "1.0"
          description: "스탭"
        url:
          type: string
          example: "/mobile/main/addition/other?type=etf&step=1"
          description: "웹페이지 경로"
        jsonData:
          type: string
          example: '{"client":{"..........":""}}'
          description: "웹 임시저장 데이터"
        custNm:
          type: string
          example: "테스트고객"
          description: "고객명"
        custMpno:
          type: string
          example: "010-1111-2222"
          description: "핸드폰 번호"
        subNo:
          type: string
          example: "19830101"
          description: "생년월일 or 사업자번호"
        email:
          type: string
          example: "abcdefg@abcd.co.kr"
          description: "Email"

    UploadTempResult:
      type: object
      properties:
        isComplete:
          type: boolean
          description: "전자문서 끝났는지 여부"

    ClearFormStepData:
      type: object
      properties:
        step:
          type: string
          example: "1.0"
          description: "스탭"


    ClearFormStepResult:
      type: object
      properties:
        isComplete:
          type: boolean
          description: "전자문서 끝났는지 여부"




  examples:
    ResponseGetEntryIdSuccess:
      value:
        result: true
        etryId: PRDPR0021234567812345620221121OD000001
    ResponseGetEntryIdFail:
      value:
        result: false
        errorMessage: 연락처 유효성 검사 실패

    RequestWritePen_pen:
      value:
        type: ""
        title: "따라쓰기"
        pen:
          id: "DDARA"
          subtitle: "따라쓰기를 해주세요."
          placeholder: "따라쓰기 입니다."

    RequestAuthCamera1:
      value:
        cameraType: "idcard"
        takeType: "ocr"
        requireIssueDate: "Y"
        requireIssueOffice: "Y"
    RequestAuthCamera2:
      value:
        cameraType: "idcard"
        takeType: "direct"
        requireIssueDate: "Y"
        requireIssueOffice: "Y"
    RequestAuthCamera3:
      value:
        cameraType: "oversea"
        takeType: "ocr"
        requireIssueDate: "Y"
        requireIssueOffice: "Y"
    RequestAuthCamera4:
      value:
        cameraType: "oversea"
        takeType: "direct"
        requireIssueDate: "Y"
        requireIssueOffice: "Y"
    RequestAuthCamera5:
      value:
        cameraType: "foreign"
        takeType: "normal"
        requireIssueDate: "Y"
        requireIssueOffice: "Y"
    RequestAuthCamera6:
      value:
        cameraType: "compatriot"
        takeType: "normal"
        requireIssueDate: "Y"
        requireIssueOffice: "Y"
    RequestAuthCamera7:
      value:
        cameraType: "passport"
        takeType: "normal"
        requireIssueDate: "Y"
        requireIssueOffice: "Y"
        